- app/models/housing.rb
- app/models/image.rb
- app/models/inventory.rb
- app/models/receipt.rb
- app/models/rental.rb
- app/models/renter.rb
- app/models/room.rb
- app/models/user.rb
- db/migrate/20180529103042_create_housings.rb
- db/migrate/20180529103110_create_rentals.rb
- db/migrate/20180529103710_create_receipts.rb
- db/migrate/20180529103836_create_renters.rb
- db/migrate/20180529104209_create_rooms.rb
- db/migrate/20180529104327_create_inventories.rb
- db/migrate/20180529104426_create_images.rb
- db/migrate/20180529123903_add_inputs_to_user.rb
- db/schema.rb
- test/models/housing_test.rb
- test/models/image_test.rb
- test/models/inventory_test.rb
- test/models/receipt_test.rb
- test/models/rental_test.rb
- test/models/renter_test.rb
- test/models/room_test.rb
This PR creates all data models and adds validations to them. It also contain the database schema.
Please: 
- check models
- check schema
- check validation
Thanks
> Add Models and validations

- app/controllers/housings_controller.rb
- app/views/housings/new.html.erb
create housings_controller & new.html.erb file for creating housing
> create housings_controller & new.html.erb file

- app/controllers/housings_controller.rb
- app/controllers/rooms_controller.rb
- app/policies/room_policy.rb
- app/views/housings/index.html.erb
- app/views/housings/new.html.erb
- app/views/rooms/new.html.erb
Create a room and identify to Housing.
> Create a room

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/housings/index.html.erb
- app/views/housings/new.html.erb
- app/views/housings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
footer mis en place sans design, il est sticky quel que soit la hauteur de content.
> Add a footer no designed yet

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/housings/new.html.erb
- app/views/layouts/application.html.erb
This PR:
* Fixes issue where footer wasn't attached to the bottom of the page (on longer pages).
* Restores deleted collection used by Simple form, for the user to pick one.
> Make the footer really sticky

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
* Adds some `margin-bottom` to the main content element.
* Fixes the display of the navbar.
* Improve CSS code.
> Improve display of navbar and footer

- app/controllers/rentals_controller.rb
- app/views/housings/show.html.erb
- app/views/rentals/_details.html.erb
- app/views/rentals/show.html.erb
adding show for rental
display rentals information
display renter information
> Add Show rental

- app/assets/stylesheets/components/_navbar.scss
- app/views/housings/_form_housing.html.erb
- app/views/housings/index.html.erb
- app/views/housings/new.html.erb
- app/views/housings/show.html.erb
- app/views/receipts/_form_receipt.html.erb
- app/views/receipts/index.html.erb
- app/views/receipts/new.html.erb
- app/views/rentals/_form_rental.html.erb
- app/views/rentals/new.html.erb
- app/views/renters/_form_renter.html.erb
- app/views/renters/new.html.erb
- app/views/rooms/_form_room.html.erb
- app/views/rooms/new.html.erb
- app/views/shared/_navbar.html.erb
* Forms are now centered and smaller thanks to Bootstrap's grid.
* Navbar is now sort of responsive thanks to flexbox.
* Also, small tweak on borders.
> Add grid to forms and make the navbar responsive

- config/routes.rb
Edit route.rb to define a different root route for logged in out users
> Define a different root route for logged in out users

- app/controllers/inventories_controller.rb
- app/models/housing.rb
- app/views/housings/show.html.erb
- app/views/inventories/new.html.erb
- app/views/inventories/show.html.erb
- config/routes.rb
la première fois le bouton est "créer", on arrive sur une page "new"
ensuite le bouton devient "afficher", on arrive sur une page "show"
> un utilisateur peut voir un état des lieux à partir du show d'un housing

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_forms.scss
- app/views/housings/index.html.erb
- app/views/housings/show.html.erb
- app/views/inventories/show.html.erb
- app/views/receipts/index.html.erb
- app/views/receipts/show.html.erb
- app/views/rentals/show.html.erb
- app/views/rooms/new.html.erb
* Adds antialiasing to fonts.
* Remove `type=button` from links, which broke the display of buttons on Chrome.
* Change font-weight of forms to normal (400).
> Improve display of type and buttons

- app/assets/stylesheets/components/_forms.scss
- app/controllers/housings_controller.rb
- app/views/housings/_form_housing.html.erb
- app/views/inventories/_form_inventory.html.erb
- app/views/receipts/_form_receipt.html.erb
- app/views/rentals/_form_rental.html.erb
- app/views/renters/_form_renter.html.erb
- app/views/rooms/_form_room.html.erb
- app/views/rooms/new.html.erb
This PR fixes an issue with `new` views where forms wouldn’t create new instances of classes.
In short, closes #73.
> Remove <form> tag on all forms

- app/views/inventories/_form_inventory.html.erb
This PR fixes the inventory form bug.
> Fix bug with inventory form

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_typography.scss
This PR darken the text of the app and especially the forms so as to look good during the demo.
> Darken text for demo

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_background_image.scss
- app/assets/stylesheets/components/_card_housing.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_typography.scss
- app/assets/stylesheets/pages/_housing.scss
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/housings/_list_housings.html.erb
- app/views/housings/index.html.erb
- app/views/housings/new.html.erb
- app/views/housings/show.html.erb
- app/views/inventories/new.html.erb
- app/views/layouts/application.html.erb
- app/views/receipts/new.html.erb
- app/views/rentals/new.html.erb
- app/views/renters/new.html.erb
- app/views/rooms/new.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
This PR adds style to some views. It's mostly frontend stuff.
> Add style to housings#index and forms

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/pages/_housing.scss
- app/views/housings/show.html.erb
- app/views/inventories/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/profiles/edit.html.erb
- app/views/receipts/index.html.erb
- app/views/receipts/show.html.erb
- app/views/rentals/show.html.erb
This PR fixes the layout of broken pages but doesn't style them that much. There's still work to be done on style of pages. Check out #91 for more information.
> Adds a container to broken pages so content gets centered

- app/models/housing.rb
- app/models/room.rb
- app/views/housings/_form_housing.html.erb
Still having issue with size of the room.
> Create validation for user inputs

- app/assets/stylesheets/components/_background_image.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/housings_controller.rb
- app/controllers/rooms_controller.rb
- app/models/housing.rb
- app/models/image.rb
- app/models/room.rb
- app/uploaders/photo_uploader.rb
- app/views/housings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/rooms/_form_room.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_navbar.html.erb
This PR adds a background image to housing#show. It takes the first image added into the room#new. Also, if there's no image attached to any room of the housing, a default background image is displayed.
> Add background image to index#show

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/rentals/_form_rental.html.erb
- package.json
- yarn.lock
the user can add a start date of rental, the end date is automatically fullfilled 1 year later for a furnished house, if not... the end date is 3 years later.
> Creation of automatic end date of rental

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_background_image.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/layouts/_index.scss
- app/assets/stylesheets/pages/_housing.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
This PR fixes the display of the navbar and the alerts generated by Devise.
> Fix navbar and alerts display

- app/views/shared/_banner.html.erb
This PR removes a `<div>` in a shared file.
> Fixes an issue where title wasn't displaying well on housing#show

- app/assets/stylesheets/components/_forms.scss
- app/models/housing.rb
- app/views/housings/_details.html.erb
- app/views/rooms/_form_room.html.erb
- app/views/rooms/new.html.erb
This is a small PR which fixes a few stuff here and there.
> Small fixes on various pages

- app/views/profiles/edit.html.erb
This PR brings the `profile#edit` view back to life. 🎉
> Fixes a bug which would break the profile#new view

- Gemfile
- Gemfile.lock
- app/controllers/inventories_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/receipts_controller.rb
- app/models/user.rb
- app/views/shared/_navbar.html.erb
If the `current_user` has a [Gravatar](https://fr.gravatar.com/) account, then the navbar displays his or her avatar.
> Fecth Gravatar image for logged user

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_typography.scss
- app/controllers/housings_controller.rb
- app/controllers/rooms_controller.rb
- app/javascript/components/photo_input.js
- app/javascript/packs/application.js
- app/models/image.rb
- app/models/room.rb
- app/views/housings/index.html.erb
- app/views/housings/new.html.erb
- app/views/rooms/_form_room.html.erb
- app/views/rooms/_show_room.html.erb
- app/views/rooms/create.js.erb
- app/views/rooms/new.html.erb
- config/application.rb
This PR adds Ajax to `room#new` view. This closes #148. This closes #135.
> Combine housing#new and room#new into two steps

- app/javascript/components/flash_clear.js
- app/javascript/packs/application.js
- app/views/shared/_flashes.html.erb
This PR closes #136. Devise alert and notice messages now disappear after 3 seconds.
> Make Devise flash messages disappear after 3 seconds

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
> Fix navbar on Receipts page and link colors on various views

- app/assets/stylesheets/config/_typography.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/housings/index.html.erb
- app/views/housings/show.html.erb
- app/views/rooms/create.js.erb
- app/views/rooms/new.html.erb
> Add a validate button on the room#new view using JS

- app/javascript/packs/application.js
- app/models/housing.rb
- app/views/housings/_list_housings.html.erb
- app/views/rentals/new.html.erb
This PR fixes a bug where maps wouldn't show up on `housing#index` view.
> Fix display of maps on housing#index

- app/views/rentals/new.html.erb
- app/views/renters/_form_renter.html.erb
- app/views/renters/new.html.erb
> Add steps to rental creation

- app/assets/stylesheets/config/_typography.scss
- app/views/rentals/new.html.erb
- app/views/renters/new.html.erb
This PR fixes a bug with rental creation form.
> Fix steps on housing rental

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_typography.scss
- app/views/housings/_details.html.erb
- app/views/housings/_list_housings.html.erb
- app/views/housings/index.html.erb
- app/views/housings/show.html.erb
- app/views/inventories/_form_inventory.html.erb
- app/views/inventories/_housing_specs.html.erb
- app/views/rentals/_housings.html.erb
- app/views/rentals/_rental.html.erb
This PR styles housing#index and fix date localisation on housing cards.
> Small frontend improvments on housing#index and housing#show

- app/assets/stylesheets/config/_typography.scss
- app/views/housings/show.html.erb
- app/views/rentals/show.html.erb
+ Change order of inventory and receipts
> Implement Success Icons if Owner signed (and renter)

- app/assets/stylesheets/pages/_rental_show.scss
- app/models/inventory.rb
- app/views/housings/index.html.erb
- app/views/inventories/_form_inventory.html.erb
- app/views/inventories/_housing_specs.html.erb
- app/views/inventories/_inventory.html.erb
- app/views/inventories/_owner_specs.html.erb
- app/views/inventories/_renter_specs.html.erb
- app/views/inventories/index.html.erb
- app/views/inventories/new.html.erb
- app/views/receipts/index.html.erb
- app/views/rentals/_rental.html.erb
- app/views/rentals/new.html.erb
- app/views/rentals/show.html.erb
This PR adds style to the inventory and the receipts (finally!).
> Add style to inventory

- app/views/housings/index.html.erb
- app/views/receipts/index.html.erb
This PR fixes the logic of the housing#index page.
> Fix housing#index conditionnal logic
